language: "node_js"

node_js:
  - "0.10"
  - "0.11"

install:
  - make sync_submodules
  - cd global
  - make clean
  - make build
  - cd ../local
  - make clean
  - make build

script:
  - make tests
  - cd ../global
  - make tests

notifications:
   email:
      - frsela@tid.es
      - gll@tid.es
